# Generated by Django 5.1.1 on 2024-12-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
