# Generated by Django 5.1.1 on 2024-12-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
