# Generated by Django 5.1.1 on 2024-12-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_followerss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followerss',
        ),
    ]
